# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tesKoding.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Nama : Khairul Fahmi
# NPM : 2210010241
# Kelas : 5P Reguler Pagi BJM
# Mata Kuliah : Pemrograman Visual 3

from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem
from datetime import datetime

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(687, 645)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 160, 161))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelNpm = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNpm.setFont(font)
        self.labelNpm.setObjectName("labelNpm")
        self.verticalLayout.addWidget(self.labelNpm)
        self.labelNama = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNama.setFont(font)
        self.labelNama.setObjectName("labelNama")
        self.verticalLayout.addWidget(self.labelNama)
        self.labelKelas = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelKelas.setFont(font)
        self.labelKelas.setObjectName("labelKelas")
        self.verticalLayout.addWidget(self.labelKelas)
        self.labelJurusan = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelJurusan.setFont(font)
        self.labelJurusan.setObjectName("labelJurusan")
        self.verticalLayout.addWidget(self.labelJurusan)
        self.labelTanggalLahir = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelTanggalLahir.setFont(font)
        self.labelTanggalLahir.setObjectName("labelTanggalLahir")
        self.verticalLayout.addWidget(self.labelTanggalLahir)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(200, 30, 471, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textNpm = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.textNpm.setObjectName("textNpm")
        self.verticalLayout_2.addWidget(self.textNpm)
        self.textNama = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.textNama.setObjectName("textNama")
        self.verticalLayout_2.addWidget(self.textNama)
        self.textKelas = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.textKelas.setObjectName("textKelas")
        self.verticalLayout_2.addWidget(self.textKelas)
        self.textJurusan = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.textJurusan.setObjectName("textJurusan")
        self.verticalLayout_2.addWidget(self.textJurusan)
        self.textTanggalLahir = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.textTanggalLahir.setObjectName("textTanggalLahir")
        self.verticalLayout_2.addWidget(self.textTanggalLahir)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 200, 651, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonSimpan = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonSimpan.setObjectName("buttonSimpan")
        self.horizontalLayout.addWidget(self.buttonSimpan)
        self.buttonUbah = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonUbah.setObjectName("buttonUbah")
        self.horizontalLayout.addWidget(self.buttonUbah)
        self.buttonHapus = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonHapus.setObjectName("buttonHapus")
        self.horizontalLayout.addWidget(self.buttonHapus)
        self.buttonLoadData = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.buttonLoadData.setObjectName("buttonLoadData")
        self.horizontalLayout.addWidget(self.buttonLoadData)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 259, 651, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 600, 651, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonCari = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.buttonCari.setObjectName("buttonCari")
        self.horizontalLayout_2.addWidget(self.buttonCari)
        self.textCari = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.textCari.setObjectName("textCari")
        self.horizontalLayout_2.addWidget(self.textCari)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # Button Handlers
        self.buttonSimpan.clicked.connect(self.insertMahasiswa)
        self.buttonLoadData.clicked.connect(self.loadMahasiswa)
        self.tableWidget.cellClicked.connect(self.getById)
        self.buttonHapus.clicked.connect(self.deleteMahasiswa)
        self.buttonUbah.clicked.connect(self.updateMahasiswa)
        self.buttonCari.clicked.connect(self.searchMahasiswa)

    # Function List
    def insertMahasiswa(self):
        npm = self.textNpm.text()
        nama = self.textNama.text()
        kelas = self.textKelas.text()
        jurusan = self.textJurusan.text()
        tanggalLahir = self.textTanggalLahir.text()

        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="db_kampus"
        )

        cursor = mydb.cursor()
        sql = "INSERT INTO mahasiswa (npm, nama, kelas, jurusan, tanggal_lahir) VALUES (%s, %s, %s, %s, %s)"
        val = (npm, nama, kelas, jurusan, tanggalLahir)
        cursor.execute(sql, val)
        mydb.commit()
        self.loadMahasiswa()
        self.textNpm.clear()
        self.textNama.clear()
        self.textKelas.clear()
        self.textJurusan.clear()
        self.textTanggalLahir.clear()

    def getById(self, row):
        npmItem = self.tableWidget.item(row, 0)
        nameItem = self.tableWidget.item(row, 1)
        kelasItem = self.tableWidget.item(row, 2)
        jurusanItem = self.tableWidget.item(row, 3)
        tanggalLahirItem = self.tableWidget.item(row, 4)

        if npmItem:
            npm = npmItem.text()
            nama = nameItem.text()
            kelas = kelasItem.text()
            jurusan = jurusanItem.text()
            tanggalLahir = tanggalLahirItem.text()
            self.textNpm.setText(npm)
            self.textNama.setText(nama)
            self.textKelas.setText(kelas)
            self.textJurusan.setText(jurusan)
            self.textTanggalLahir.setText(tanggalLahir)

    def updateMahasiswa(self):
        npm = self.textNpm.text()
        nama = self.textNama.text()
        kelas = self.textKelas.text()
        jurusan = self.textJurusan.text()
        tanggalLahir = self.textTanggalLahir.text()

        if not npm or not nama or not kelas or not jurusan or not tanggalLahir:
            return 

        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="db_kampus"
        )
        cursor = mydb.cursor()
        sql = "UPDATE mahasiswa SET nama = %s, kelas = %s, jurusan = %s, tanggal_lahir = %s WHERE npm = %s"
        val = (nama, kelas, jurusan, tanggalLahir, npm)
        cursor.execute(sql, val)
        mydb.commit()
        self.loadMahasiswa()

    def deleteMahasiswa(self):
        npm = self.textNpm.text().strip()
        if not npm:
            QtWidgets.QMessageBox.warning(
                None, "Peringatan", "NPM tidak boleh kosong!"
            )
            return

        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_kampus"
            )
            cursor = mydb.cursor()

            sql = "DELETE FROM mahasiswa WHERE npm = %s"
            val = (npm,)
            cursor.execute(sql, val)
            mydb.commit()

            if cursor.rowcount > 0:
                QtWidgets.QMessageBox.information(
                    None, "Informasi", f"Data dengan NPM {npm} berhasil dihapus!"
                )
            else:
                QtWidgets.QMessageBox.warning(
                    None, "Peringatan", f"Data dengan NPM {npm} tidak ditemukan!"
                )

            self.loadMahasiswa()
            self.textNpm.clear()
            self.textNama.clear()
            self.textKelas.clear()
            self.textJurusan.clear()
            self.textTanggalLahir.clear()
        except mc.Error as e:
            QtWidgets.QMessageBox.critical(
                None, "Kesalahan", f"Terjadi kesalahan saat menghapus data: {str(e)}"
            )
        finally:
            if mydb.is_connected():
                cursor.close()
                mydb.close()

    def loadMahasiswa(self):
        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="db_kampus"
        )

        mycursor = mydb.cursor()
        mycursor.execute("SELECT * FROM mahasiswa ORDER BY npm ASC")
        result = mycursor.fetchall()
        self.tableWidget.setRowCount(0)
        if result:
            self.tableWidget.setColumnCount(len(result[0]))
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
    

    def searchMahasiswa(self):
        keyword = self.textCari.text().strip() 
        if not keyword:
            return  

        mydb = mc.connect(
            host="localhost",
            user="root",
            password="",
            database="db_kampus"
        )

        cursor = mydb.cursor()

        search_pattern = f"%{keyword}%"
        try:
            parsed_date = datetime.strptime(keyword, "%d-%m-%Y").strftime("%Y-%m-%d")
            search_pattern_date = f"%{parsed_date}%"
        except ValueError:
            search_pattern_date = search_pattern

        sql = """
        SELECT * FROM mahasiswa 
        WHERE npm LIKE %s OR nama LIKE %s OR kelas LIKE %s 
        OR jurusan LIKE %s OR tanggal_lahir LIKE %s
        """
        val = (search_pattern, search_pattern, search_pattern, search_pattern, search_pattern_date)
        cursor.execute(sql, val)
        result = cursor.fetchall()

        self.tableWidget.setRowCount(0)
        if result:
            self.tableWidget.setColumnCount(len(result[0]))
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
        else:
            self.tableWidget.setColumnCount(0) 

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelNpm.setText(_translate("Form", "NPM"))
        self.labelNama.setText(_translate("Form", "Nama"))
        self.labelKelas.setText(_translate("Form", "Kelas"))
        self.labelJurusan.setText(_translate("Form", "Jurusan"))
        self.labelTanggalLahir.setText(_translate("Form", "Tanggal Lahir"))
        self.buttonSimpan.setText(_translate("Form", "Simpan"))
        self.buttonUbah.setText(_translate("Form", "Ubah"))
        self.buttonHapus.setText(_translate("Form", "Hapus"))
        self.buttonLoadData.setText(_translate("Form", "Load Data"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "NPM"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Kelas"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Jurusan"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tanggal Lahir"))
        self.buttonCari.setText(_translate("Form", "Cari"))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelNpm.setText(_translate("Form", "NPM"))
        self.labelNama.setText(_translate("Form", "Nama"))
        self.labelKelas.setText(_translate("Form", "Kelas"))
        self.labelJurusan.setText(_translate("Form", "Jurusan"))
        self.labelTanggalLahir.setText(_translate("Form", "Tanggal Lahir"))
        self.buttonSimpan.setText(_translate("Form", "Simpan"))
        self.buttonUbah.setText(_translate("Form", "Ubah"))
        self.buttonHapus.setText(_translate("Form", "Hapus"))
        self.buttonLoadData.setText(_translate("Form", "Load Data"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "NPM"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Kelas"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Jurusan"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tanggal Lahir"))
        self.buttonCari.setText(_translate("Form", "Cari"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
